package_assets: off
embed_assets: on
compress_assets: off
gzip_assets: on
template_function: _.template
package_path: packages
javascript_compressor: closure
#compressor_options:
#    compilation_level: ADVANCED_OPTIMIZATIONS

javascripts:
    app:
        - public/javascripts/jquery-1.5.1.js
        - public/javascripts/json2.js
        - public/javascripts/underscore-1.1.4.js
        - public/javascripts/jquery-ui-1.8.9.custom.min.js
        - public/javascripts/backbone-0.3.3.js
        - public/javascripts/ICanHaz-0.9.js
        - public/javascripts/jquery.ba-dotimeout.js
        - public/javascripts/application.js
        - public/javascripts/controllers/*.js
        - public/javascripts/views/*.js
        - public/javascripts/models/*.js
        - public/javascripts/collections/*.js

stylesheets:
    common:
        - public/stylesheets/reset.css
    app:
        - public/stylesheets/scaffold.css
